import {database} from '../../../db/raw';
import {access,sameOrigin,routeError,auditStatement,AccessError} from '../../../lib/access';
import {validateEntity,computeAssessment,Entity} from '../../../lib/learning';
import {mayView,mayWrite,manages} from '../../../lib/permissions';
export async function GET(){try{const a=await access();const r=await database().prepare('SELECT * FROM learning_entities WHERE owner=? ORDER BY updated DESC').bind(a.ownerId).all();const all:Entity[]=r.results.map((x:any)=>({...x,data:JSON.parse(x.payload),payload:undefined,owner:undefined}));const entities=all.filter(x=>mayView(a,x,all)).map(x=>{if(!manages(a)&&x.kind==='course')return {...x,data:{...x.data,questions:x.data.questions.map((q:any)=>({question:q.question,options:q.options}))}};return x});return Response.json({entities,access:a},{headers:{'Cache-Control':'no-store'}})}catch(e){return routeError(e)}}
export async function POST(req:Request){try{const a=await access();sameOrigin(req);const p:any=await req.json();if(!p||JSON.stringify(p).length>60000)throw new AccessError('El registro excede el tamaño permitido.',400);const db=database();const list=await db.prepare('SELECT * FROM learning_entities WHERE owner=?').bind(a.ownerId).all();const entities:Entity[]=list.results.map((x:any)=>({...x,data:JSON.parse(x.payload)}));const old=p.id?entities.find(x=>x.id===p.id):null;if(p.id&&!old)throw new AccessError('Registro no disponible.',404);if(old&&!mayView(a,old,entities))throw new AccessError('No tienes acceso a este registro.');if(old&&old.kind!==p.kind)throw new AccessError('Categoría incompatible.',400);if(old&&['assignment','read','attempt','application','diagnosis'].includes(old.kind))throw new AccessError('Este registro conserva su historial y no puede editarse.',400);const data=validateEntity(p.kind,{...p.data,id:p.id},entities);if(!mayWrite(a,p.kind,data,entities))throw new AccessError('No tienes permiso para realizar esta acción.');if(p.kind==='process'){data.reviewState=p.data.reviewState==='In review'?'In review':'Draft';data.submittedBy=a.userId;data.createdBy=old?.data.createdBy||a.userId;data.fileId=p.data.fileId||'';if(data.fileId){const f:any=await db.prepare('SELECT * FROM stored_files WHERE id=? AND owner=?').bind(data.fileId,a.ownerId).first();if(!f||f.space!==data.space||f.area!==data.area)throw new AccessError('El archivo no pertenece al hospital del proceso.',400)}if(old){const changed=['title','url','version','criteria','fileId'].some(k=>JSON.stringify(old.data[k])!==JSON.stringify(data[k]));if(changed&&old.data.version===data.version)throw new AccessError('Cambia la versión al actualizar el contenido.',400);if(old.data.space!==data.space&&entities.some(x=>x.data.processId===old.id))throw new AccessError('Un proceso vinculado debe conservar su hospital.',400)}}
if(['assignment','read','attempt','course','checklist'].includes(p.kind)){const process=entities.find(x=>x.id===data.processId&&x.kind==='process');if(!process||process.data.reviewState!=='Approved')throw new AccessError('El proceso debe estar aprobado por Calidad antes de usarlo.',400);if(process.data.validUntil<new Date().toISOString().slice(0,10))throw new AccessError('La vigencia del proceso ha vencido. Actualízalo antes de usarlo.',400)}
if(p.kind==='course')data.maxAttempts=Number.isInteger(p.data.maxAttempts)&&p.data.maxAttempts>=1&&p.data.maxAttempts<=10?p.data.maxAttempts:3;
if(p.kind==='attempt'){const course=entities.find(x=>x.id===data.courseId)!;const previous=entities.filter(x=>x.kind==='attempt'&&x.data.courseId===course.id&&x.data.employeeId===data.employeeId&&(!course.updated||!x.created||x.created>=course.updated));if(previous.length>=(course.data.maxAttempts||3))throw new AccessError('Se alcanzó el límite de intentos para esta evaluación.',409);Object.assign(data,computeAssessment(data,entities));const employee=entities.find(x=>x.id===data.employeeId)!;data.employeeName=employee.data.name;data.employeeNumber=employee.data.number;data.actor=a.email;data.method=a.role==='collaborator'?'Evaluación individual':'Aplicación asistida por administrador';if(data.passed)data.certificateId=crypto.randomUUID()}
if(p.kind==='read'){data.actor=a.email;data.method=a.role==='collaborator'?'Declaración de lectura del colaborador':'Registro asistido por administrador'}
if(p.kind==='reference'){data.createdBy=old?.data.createdBy||a.userId;data.submittedBy=a.userId;if(data.status==='Validado')throw new AccessError('Envía la referencia a revisión para que Calidad la valide.',400)}
if(p.kind==='employee'&&old&&old.data.space!==data.space&&entities.some(x=>x.data.employeeId===old.id))throw new AccessError('Conserva el hospital del colaborador para mantener su historial.',400);
if(p.kind==='assignment'&&entities.some(x=>x.kind==='assignment'&&x.id!==p.id&&x.data.processId===data.processId&&x.data.employeeId===data.employeeId&&x.data.version===data.version))throw new AccessError('Esta versión ya está asignada a esa persona.',409);
if(p.kind==='read'&&entities.some(x=>x.kind==='read'&&x.data.assignmentId===data.assignmentId&&x.data.version===data.version))throw new AccessError('La lectura ya está registrada.',409);
const attemptCourse=entities.find(x=>x.id===data.courseId&&x.kind==='course');const attemptCount=entities.filter(x=>x.kind==='attempt'&&x.data.courseId===data.courseId&&x.data.employeeId===data.employeeId&&(!attemptCourse?.updated||!x.created||x.created>=attemptCourse.updated)).length;const stableKey=p.kind==='attempt'?[a.ownerId,p.kind,data.courseId,data.employeeId,attemptCourse?.updated||'',attemptCount]:p.kind==='assignment'?[a.ownerId,p.kind,data.processId,data.employeeId,data.version]:p.kind==='read'?[a.ownerId,p.kind,data.assignmentId,data.version]:null;const digest=stableKey?await crypto.subtle.digest('SHA-256',new TextEncoder().encode(JSON.stringify(stableKey))):null;const id=p.id||(digest?Array.from(new Uint8Array(digest)).map(x=>x.toString(16).padStart(2,'0')).join(''):crypto.randomUUID()),now=new Date().toISOString(),payload=JSON.stringify(data);
await db.batch([db.prepare(['assignment','read','attempt','application','diagnosis'].includes(p.kind)?'INSERT INTO learning_entities (id,owner,kind,payload,created,updated) VALUES (?,?,?,?,?,?)':'INSERT INTO learning_entities (id,owner,kind,payload,created,updated) VALUES (?,?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET payload=excluded.payload,updated=excluded.updated').bind(id,a.ownerId,p.kind,payload,old?.created||now,now),auditStatement(a,id,(old?'Actualización':'Creación')+' · '+p.kind,old?.data,data,data.space)]);return Response.json({ok:true,id,data})}catch(e){return routeError(e)}}
