import fs from 'node:fs';import path from 'node:path';import assert from 'node:assert/strict';import ts from 'typescript';import {DatabaseSync} from 'node:sqlite';import {createRequire} from 'node:module';
const native=createRequire(import.meta.url),sql=new DatabaseSync(':memory:');for(const f of fs.readdirSync('drizzle').filter(f=>f.endsWith('.sql')).sort())sql.exec(fs.readFileSync('drizzle/'+f,'utf8'));
function statement(query){let args=[];return {bind(...a){args=a;return this},async first(){return sql.prepare(query).get(...args)||null},async all(){return {results:sql.prepare(query).all(...args)}},async run(){return sql.prepare(query).run(...args)}}}const db={prepare:statement,async batch(stmts){sql.exec('BEGIN');try{for(const s of stmts)await s.run();sql.exec('COMMIT')}catch(e){sql.exec('ROLLBACK');throw e}}};
const env={DB:db,ORG_OWNER_EMAIL:'owner@test.example',AUTH_SETUP_TOKEN:'test-only-setup-key-with-32-characters'};let cookie='';const cache=new Map();function load(file){file=path.resolve(file);if(cache.has(file))return cache.get(file).exports;const module={exports:{}};cache.set(file,module);const source=ts.transpileModule(fs.readFileSync(file,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText;const require=name=>{if(name==='cloudflare:workers')return {env};if(name==='next/headers')return {headers:async()=>new Headers({cookie,'x-chatgpt-user-id':'spoof'})};if(name.startsWith('.'))return load(path.resolve(path.dirname(file),name.endsWith('.ts')?name:name+'.ts'));return native(name)};new Function('module','exports','require',source)(module,module.exports,require);return module.exports}
const auth=load('lib/auth.ts'),access=load('lib/access.ts'),passwords=load('lib/passwords.ts');const routes=Object.fromEntries(['setup','login','activate','invite','password','logout'].map(x=>[x,load('app/api/auth/'+x+'/route.ts')]));const origin='https://test.example',strong='My unique phrase 2026!';async function post(name,p={},requestOrigin=origin){const r=await routes[name].POST(new Request(origin+'/api/auth/'+name,{method:'POST',headers:{'Content-Type':'application/json',Origin:requestOrigin,cookie},body:JSON.stringify(p)}));let data;try{data=await r.clone().json()}catch{}return {r,status:r.status,data,cookie:r.headers.get('set-cookie')?.split(';')[0]}};
assert.equal(await auth.getCurrentUser(),null);assert.equal((await post('setup',{},'https://evil.example')).status,403);assert.equal((await post('setup',{setupToken:'wrong',email:env.ORG_OWNER_EMAIL,password:strong})).status,403);assert.equal((await post('setup',{setupToken:env.AUTH_SETUP_TOKEN,email:env.ORG_OWNER_EMAIL,password:'short'})).status,400);
let result=await post('setup',{setupToken:env.AUTH_SETUP_TOKEN,email:env.ORG_OWNER_EMAIL,password:strong,name:'Owner'});assert.equal(result.status,200);cookie=result.cookie;assert.match(result.r.headers.get('set-cookie'),/HttpOnly.*SameSite=Lax.*Secure/);const owner=await auth.getCurrentUser();assert(owner);assert.equal((await access.access()).role,'owner');assert.equal((await post('setup',{setupToken:env.AUTH_SETUP_TOKEN,email:env.ORG_OWNER_EMAIL,password:strong})).status,409);assert.notEqual(sql.prepare('SELECT password_hash FROM auth_users').get().password_hash,strong);
assert.equal((await post('login',{email:env.ORG_OWNER_EMAIL,password:'wrong'})).status,401);result=await post('login',{email:env.ORG_OWNER_EMAIL,password:strong});assert.equal(result.status,200);cookie=result.cookie;const oldCookie=cookie;
const now=new Date().toISOString();sql.prepare('INSERT INTO memberships (id,owner,email,user_id,name,role,spaces,areas,employee_id,active,created,updated) VALUES (?,?,?,?,?,?,?,?,?,?,?,?)').run('member',owner.userId,'user@test.example','','User','quality','["1"]','[]','','1',now,now);
result=await post('invite',{email:'user@test.example'});assert.equal(result.status,200);const activation=result.data.url.split('#')[1];assert.equal(sql.prepare('SELECT token_hash FROM auth_tokens').get().token_hash,await passwords.tokenHash(activation));cookie='';result=await post('activate',{token:activation,password:strong});assert.equal(result.status,200);cookie=result.cookie;assert.deepEqual((await access.access()).spaces,['1']);assert.equal((await post('activate',{token:activation,password:strong})).status,400);assert.equal((await post('invite',{email:env.ORG_OWNER_EMAIL})).status,403);
const memberCookie=cookie;cookie=oldCookie;result=await post('invite',{email:'user@test.example'});const reset=result.data.url.split('#')[1];cookie='';result=await post('activate',{token:reset,password:'A different long phrase!'});assert.equal(result.status,200);const resetCookie=result.cookie;cookie=memberCookie;assert.equal(await auth.getCurrentUser(),null);cookie=resetCookie;sql.prepare('UPDATE memberships SET active=? WHERE id=?').run('0','member');await assert.rejects(()=>access.access(),e=>e.status===403);assert.equal((await post('login',{email:'user@test.example',password:'A different long phrase!'})).status,401);sql.prepare('UPDATE memberships SET active=? WHERE id=?').run('1','member');
result=await post('password',{currentPassword:'A different long phrase!',password:'Another unique phrase 2026!'});assert.equal(result.status,200);cookie=resetCookie;assert.equal(await auth.getCurrentUser(),null);cookie=result.cookie;assert(await auth.getCurrentUser());result=await post('logout');assert.equal(result.status,303);assert.equal(result.r.headers.get('location'),'/login');assert.equal(await auth.getCurrentUser(),null);
cookie='';for(let i=0;i<10;i++)assert.equal((await post('login',{email:'unknown@test.example',password:strong})).status,401);assert.equal((await post('login',{email:'unknown@test.example',password:strong})).status,429);cookie=oldCookie.replace('__Host-slh_session','slh_dev_session');assert.equal(await auth.getCurrentUser(),null);cookie='__Host-slh_session='+ 'x'.repeat(43);assert.equal(await auth.getCurrentUser(),null);cookie=oldCookie;sql.prepare('UPDATE auth_sessions SET expires=?').run('2000-01-01T00:00:00.000Z');assert.equal(await auth.getCurrentUser(),null);
console.log('Authentication passed: owner setup, password policy, CSRF, hashed passwords/tokens, secure sessions, activation/reset once, scoped membership, suspension, session revocation, expiry and throttling.');
