import {env} from 'cloudflare:workers';
import {getChatGPTUser} from '../app/chatgpt-auth';
import {database} from '../db/raw';
import {Access} from './permissions';
export class AccessError extends Error{constructor(message:string,public status=403){super(message)}}
export async function access():Promise<Access>{const u=await getChatGPTUser();if(!u)throw new AccessError('Inicia sesión para continuar.',401);const db=database();let org:any=await db.prepare('SELECT * FROM organizations WHERE id=?').bind('main').first();if(!org){if(!env.ORG_OWNER_EMAIL||u.email.toLowerCase()!==env.ORG_OWNER_EMAIL.toLowerCase())throw new AccessError('El propietario debe inicializar la plataforma.');await db.prepare('INSERT OR IGNORE INTO organizations (id,owner_id,owner_email,created) VALUES (?,?,?,?)').bind('main',u.userId,u.email,new Date().toISOString()).run();org=await db.prepare('SELECT * FROM organizations WHERE id=?').bind('main').first()}
if(org.owner_id===u.userId)return {ownerId:org.owner_id,userId:u.userId,email:u.email,name:u.displayName,role:'owner',spaces:['1','2','3','4'],areas:[],employeeId:''};const m:any=await db.prepare('SELECT * FROM memberships WHERE owner=? AND email=? AND active=?').bind(org.owner_id,u.email.toLowerCase(),'1').first();if(!m||m.user_id&&m.user_id!==u.userId)throw new AccessError('Tu cuenta no tiene acceso autorizado. Contacta al administrador.');if(!m.user_id)await db.prepare('UPDATE memberships SET user_id=? WHERE id=? AND user_id=?').bind(u.userId,m.id,'').run();const bound:any=await db.prepare('SELECT user_id FROM memberships WHERE id=?').bind(m.id).first();if(bound.user_id!==u.userId)throw new AccessError('La cuenta ya está vinculada a otra identidad.');return {ownerId:org.owner_id,userId:u.userId,email:u.email,name:m.name||u.displayName,role:m.role,spaces:JSON.parse(m.spaces),areas:JSON.parse(m.areas),employeeId:m.employee_id}}
export function sameOrigin(req:Request){const origin=req.headers.get('origin');if(origin&&origin!==new URL(req.url).origin)throw new AccessError('Solicitud no permitida.')}
export function routeError(e:unknown){if(e instanceof AccessError)return Response.json({error:e.message},{status:e.status});console.error(e);const v=e instanceof Error&&e.name==='ValidationError';return Response.json({error:v?(e as Error).message:'No fue posible completar la operación. Intenta de nuevo.'},{status:v?400:503})}
export function auditStatement(a:Access,record:string,action:string,before:any,after:any,space=''){return database().prepare('INSERT INTO quality_audit (id,owner,record,action,before,after,at,actor,space) VALUES (?,?,?,?,?,?,?,?,?)').bind(crypto.randomUUID(),a.ownerId,record,action,JSON.stringify(before??{}),JSON.stringify(after??{}),new Date().toISOString(),a.email,space)}
