import {headers} from 'next/headers';
import {database} from '../db/raw';
import {token,tokenHash} from './passwords';
export type AppUser={userId:string;email:string;displayName:string};
export function sessionToken(cookie:string,allowDev=false){return cookie.split(';').map(x=>x.trim()).find(x=>x.startsWith('__Host-slh_session='))?.slice('__Host-slh_session='.length)||(allowDev?cookie.split(';').map(x=>x.trim()).find(x=>x.startsWith('slh_dev_session='))?.slice('slh_dev_session='.length):'')||'';}
export async function getCurrentUser():Promise<AppUser|null>{const h=await headers();const t=sessionToken(h.get('cookie')||'',process.env.NODE_ENV==='development');if(!/^[A-Za-z0-9_-]{43}$/.test(t))return null;const row:any=await database().prepare('SELECT u.id,u.email,u.name FROM auth_sessions s JOIN auth_users u ON u.id=s.user_id WHERE s.token_hash=? AND s.expires>?').bind(await tokenHash(t),new Date().toISOString()).first();if(!row)return null;return {userId:row.id,email:row.email,displayName:row.name||row.email};}
export async function newSession(userId:string){const value=token(),now=new Date(),expires=new Date(now.getTime()+8*60*60*1000).toISOString();await database().prepare('INSERT INTO auth_sessions (token_hash,user_id,created,expires) VALUES (?,?,?,?)').bind(await tokenHash(value),userId,now.toISOString(),expires).run();return value;}
export function sessionCookie(req:Request,value:string,clear=false){const u=new URL(req.url),dev=u.protocol==='http:'&&['localhost','127.0.0.1','[::1]'].includes(u.hostname);if(u.protocol!=='https:'&&!dev)throw Error('El inicio de sesión requiere HTTPS.');return `${dev?'slh_dev_session':'__Host-slh_session'}=${value}; Path=/; HttpOnly; SameSite=Lax; Max-Age=${clear?0:28800}${dev?'':'; Secure'}`;}
export function authOrigin(req:Request){const origin=req.headers.get('origin');if(origin!==new URL(req.url).origin)throw new AuthError('Solicitud no permitida.',403);}
export class AuthError extends Error{constructor(message:string,public status=400){super(message)}}
export function authError(e:unknown){if(e instanceof Error&&e.name==='PasswordPolicyError')return Response.json({error:e.message},{status:400,headers:{'Cache-Control':'no-store'}});if(e instanceof AuthError)return Response.json({error:e.message},{status:e.status,headers:{'Cache-Control':'no-store'}});console.error(e instanceof Error?e.message:'Authentication error');return Response.json({error:'No fue posible completar la operación. Intenta de nuevo.'},{status:503,headers:{'Cache-Control':'no-store'}});}
export async function throttle(key:string,max=10){const db=database(),now=new Date(),expires=new Date(now.getTime()+15*60*1000).toISOString();const hash=await tokenHash(key);const rows=await db.prepare('INSERT INTO auth_limits (key,attempts,expires) VALUES (?,1,?) ON CONFLICT(key) DO UPDATE SET attempts=CASE WHEN expires<? THEN 1 ELSE attempts+1 END,expires=CASE WHEN expires<? THEN excluded.expires ELSE expires END RETURNING attempts').bind(hash,expires,now.toISOString(),now.toISOString()).all();if(Number((rows.results[0] as any).attempts)>max)throw new AuthError('Demasiados intentos. Espera 15 minutos antes de continuar.',429);}
export async function authBody(req:Request){authOrigin(req);if(Number(req.headers.get('content-length')||0)>4096)throw new AuthError('Solicitud demasiado grande.');const text=await req.text();if(text.length>4096)throw new AuthError('Solicitud demasiado grande.');try{return JSON.parse(text)}catch{throw new AuthError('Solicitud inválida.');}}
export function normalizedEmail(v:unknown){if(typeof v!=='string'||v.length>254||!/^\S+@\S+\.\S+$/.test(v.trim()))throw new AuthError('Revisa el correo electrónico.');return v.trim().toLowerCase();}
