export type Entity={id:string;kind:string;data:any;created?:string;updated?:string};
function fail(s:string):never{const e=new Error(s);e.name='ValidationError';throw e}
function str(v:any,label:string,required=false,max=4000){if(typeof v!=='string'||v.length>max||(required&&!v.trim()))fail('Revisa '+label+'.');return v.trim()}
function url(v:any,required=false){const s=str(v,'enlace',required,1500);if(s){try{if(new URL(s).protocol!=='https:')fail('El enlace debe usar HTTPS.')}catch{fail('Introduce un enlace HTTPS válido.')}}return s}
function date(v:any){const s=str(v,'fecha',true,10);if(!/^\d{4}-\d{2}-\d{2}$/.test(s)||!Number.isFinite(Date.parse(s))||new Date(s).toISOString().slice(0,10)!==s)fail('Introduce una fecha válida.');return s}
function pick(v:any,vs:string[],label:string){if(!vs.includes(v))fail('Revisa '+label+'.');return v}
export function validateEntity(kind:string,d:any,entities:Entity[]){if(!d||typeof d!=='object')fail('Datos inválidos.');const ref=(id:any,k:string)=>{const x=entities.find(x=>x.id===id&&x.kind===k);if(!x)fail('No se encontró el registro relacionado.');return x};const space=()=>pick(d.space,['1','2','3','4'],'hospital');const text=(k:string,required=false)=>str(d[k],k,required);let out:any;
switch(kind){
case 'employee':out={space:space(),name:text('name',true),number:text('number',true),job:text('job',true),area:text('area',true),shift:pick(d.shift,['Matutino','Vespertino','Nocturno','Mixto'],'turno'),type:pick(d.type,['Base','Eventual','Honorarios','Otro'],'tipo de personal')};if(entities.some(x=>x.kind==='employee'&&x.data.number===out.number&&x.data.space===out.space&&x.id!==d.id))fail('El número de empleado ya está registrado en ese hospital.');break;
case 'process':out={space:space(),scope:pick(d.scope,['MOCEBPASS','Farmacia'],'módulo'),code:text('code',true),title:text('title',true),axis:text('axis'),component:text('component'),job:text('job',true),area:text('area',true),docType:pick(d.docType,['Procedimiento','Política','PNO','Formato','Manual','Otro'],'tipo documental'),classification:pick(d.classification,['Indispensable','Necesario','Deseable'],'clasificación'),version:text('version',true),validUntil:date(d.validUntil),url:url(d.url,true),criteria:text('criteria'),notes:text('notes')};break;
case 'assignment':{const p=ref(d.processId,'process'),e=ref(d.employeeId,'employee');if(p.data.space!==e.data.space)fail('El proceso y la persona deben pertenecer al mismo hospital.');out={space:p.data.space,processId:p.id,employeeId:e.id,version:p.data.version,due:date(d.due)};break}
case 'read':{const a=ref(d.assignmentId,'assignment'),p=ref(a.data.processId,'process');if(a.data.version!==p.data.version)fail('La asignación pertenece a una versión anterior. Asigna la nueva versión.');out={space:a.data.space,assignmentId:a.id,processId:p.id,employeeId:a.data.employeeId,version:a.data.version,notes:text('notes'),method:'Registro asistido por administrador'};break}
case 'course':{const p=ref(d.processId,'process');if(!Array.isArray(d.questions)||!d.questions.length||d.questions.length>30)fail('Agrega entre 1 y 30 preguntas.');const questions=d.questions.map((q:any)=>{const question=str(q.question,'pregunta',true,500);if(!Array.isArray(q.options)||q.options.length!==4)fail('Cada pregunta requiere cuatro opciones.');const options=q.options.map((s:any)=>str(s,'opción',true,500));if(!Number.isInteger(q.correct)||q.correct<0||q.correct>3)fail('Selecciona la respuesta correcta.');return {question,options,correct:q.correct}});if(!Number.isFinite(d.threshold)||d.threshold<1||d.threshold>100)fail('La calificación mínima debe estar entre 1 y 100.');out={space:p.data.space,processId:p.id,version:p.data.version,title:text('title',true),resourceUrl:url(d.resourceUrl),threshold:d.threshold,questions};break}
case 'attempt':{const c=ref(d.courseId,'course'),e=ref(d.employeeId,'employee'),p=ref(c.data.processId,'process');if(c.data.space!==e.data.space)fail('Selecciona una persona del mismo hospital.');if(c.data.version!==p.data.version)fail('Actualiza el curso para la versión vigente del proceso.');if(!entities.some(x=>x.kind==='assignment'&&x.data.employeeId===e.id&&x.data.processId===p.id&&x.data.version===p.data.version))fail('Asigna primero este proceso a la persona.');if(!Array.isArray(d.answers)||d.answers.length!==c.data.questions.length||d.answers.some((v:any)=>!Number.isInteger(v)||v<0||v>3))fail('Responde todas las preguntas.');out={space:c.data.space,courseId:c.id,processId:p.id,employeeId:e.id,version:c.data.version,answers:d.answers,method:'Aplicación asistida por administrador'};break}
case 'checklist':{const p=ref(d.processId,'process');const items=text('items',true).split('\n').map(s=>s.trim()).filter(Boolean);if(!items.length||items.length>50)fail('Agrega entre 1 y 50 criterios.');out={space:p.data.space,processId:p.id,version:p.data.version,title:text('title',true),items};break}
case 'application':{const c=ref(d.checklistId,'checklist'),p=ref(c.data.processId,'process');if(c.data.version!==p.data.version)fail('Actualiza la cédula para la versión vigente.');if(!Array.isArray(d.answers)||d.answers.length!==c.data.items.length||d.answers.some((s:any)=>!['Cumple','No cumple','No aplica'].includes(s)))fail('Responde todos los criterios.');const applies=d.answers.filter((s:string)=>s!=='No aplica');out={space:c.data.space,checklistId:c.id,processId:p.id,version:c.data.version,evaluator:text('evaluator',true),area:text('area',true),date:date(d.date),answers:d.answers,items:c.data.items,title:c.data.title,evidence:url(d.evidence),notes:text('notes'),percent:applies.length?Math.round(d.answers.filter((s:string)=>s==='Cumple').length/applies.length*100):null};if(d.answers.includes('No aplica')&&!out.notes)fail('Justifica los criterios no aplicables.');break}
case 'reference':{const p=ref(d.processId,'process');out={space:p.data.space,processId:p.id,title:text('title',true),priority:pick(d.priority,['Indispensable','Necesario','Deseable'],'prioridad'),responsible:text('responsible',true),due:date(d.due),status:pick(d.status,['Pendiente','En proceso','En revisión','Validado'],'estado'),evidence:url(d.evidence),notes:text('notes')};if(out.status==='Validado'&&!out.evidence)fail('Agrega evidencia para validar.');break}
case 'diagnosis':{const p=ref(d.processId,'process');const criteria=p.data.criteria.split('\n').map((s:string)=>s.trim()).filter(Boolean);if(!criteria.length)fail('Agrega criterios de diagnóstico al proceso.');if(!Array.isArray(d.answers)||d.answers.length!==criteria.length||d.answers.some((s:any)=>!['Cumple','Parcial','No cumple','No aplica'].includes(s)))fail('Responde todos los criterios.');out={space:p.data.space,processId:p.id,version:p.data.version,evaluator:text('evaluator',true),date:date(d.date),criteria,answers:d.answers,evidence:url(d.evidence),notes:text('notes')};if(d.answers.includes('No aplica')&&!out.notes)fail('Justifica lo que no aplica.');break}
default:fail('Categoría inválida.');}
return out}
export function computeAssessment(d:any,entities:Entity[]){const c=entities.find(x=>x.id===d.courseId&&x.kind==='course')!;const questions=c.data.questions;const correct=questions.filter((q:any,i:number)=>q.correct===d.answers[i]).length;const score=Math.round(correct/questions.length*100);return {score,passed:score>=c.data.threshold,threshold:c.data.threshold,correct,total:questions.length,courseTitle:c.data.title,questions:questions.map((q:any)=>({question:q.question,options:q.options}))}}
export function employeeStats(employee:Entity,entities:Entity[]){const assigned=entities.filter(x=>x.kind==='assignment'&&x.data.employeeId===employee.id&&entities.some(p=>p.kind==='process'&&p.id===x.data.processId&&p.data.version===x.data.version));const read=assigned.filter(a=>entities.some(x=>x.kind==='read'&&x.data.assignmentId===a.id&&x.data.version===a.data.version)).length;const courses=entities.filter(c=>c.kind==='course'&&assigned.some(a=>a.data.processId===c.data.processId&&a.data.version===c.data.version));const passed=courses.filter(c=>entities.some(x=>x.kind==='attempt'&&x.data.courseId===c.id&&x.data.employeeId===employee.id&&x.data.version===c.data.version&&x.data.passed&&(!c.updated||!x.created||x.created>=c.updated))).length;return {assigned:assigned.length,read,percent:assigned.length?Math.round(read/assigned.length*100):null,courses:courses.length,passed,approval:courses.length?Math.round(passed/courses.length*100):null}}
