import type {Entity} from './learning';
export type Access={ownerId:string;userId:string;email:string;name:string;role:string;spaces:string[];areas:string[];employeeId:string};
export const roles=['admin','quality','supervisor','collaborator','direction'];
export function manages(a:Access){return ['owner','admin','quality'].includes(a.role)}
export function inScope(a:Access,space:string,area?:string){return a.spaces.includes(space)&&(!area||!a.areas.length||a.areas.includes(area)||a.role==='owner')}
export function mayReview(a:Access){return ['owner','admin','quality'].includes(a.role)}
export function mayView(a:Access,e:Entity,all:Entity[]){const parent=e.data.processId?all.find(x=>x.id===e.data.processId&&x.kind==='process'):undefined;if(!inScope(a,e.data.space,e.data.area)||parent&&!inScope(a,parent.data.space,parent.data.area))return false;if(a.role!=='collaborator')return true;if(e.kind==='employee')return e.id===a.employeeId;if(['assignment','read','attempt'].includes(e.kind))return e.data.employeeId===a.employeeId;const p=e.kind==='process'?e:all.find(x=>x.id===e.data.processId&&x.kind==='process');if(!p||p.data.reviewState!=='Approved')return false;return ['process','course'].includes(e.kind)&&all.some(x=>x.kind==='assignment'&&x.data.employeeId===a.employeeId&&x.data.processId===p.id&&x.data.version===p.data.version)}
export function mayWrite(a:Access,kind:string,data:any,all:Entity[]){const parent=data.processId?all.find(x=>x.id===data.processId&&x.kind==='process'):undefined;const employee=data.employeeId?all.find(x=>x.id===data.employeeId&&x.kind==='employee'):undefined;if(!inScope(a,data.space,data.area)||parent&&!inScope(a,parent.data.space,parent.data.area)||employee&&!inScope(a,employee.data.space,employee.data.area))return false;if(manages(a))return true;if(a.role==='direction')return false;if(a.role==='supervisor')return ['reference','diagnosis','application','read','attempt'].includes(kind);if(a.role==='collaborator')return ['read','attempt'].includes(kind)&&data.employeeId===a.employeeId&&all.some(x=>x.kind==='process'&&x.id===data.processId&&x.data.reviewState==='Approved');return false}
export function mayRecord(a:Access,r:any){return a.role!=='collaborator'&&inScope(a,r.space,r.area)}
export function reviewDecision(a:Access,submittedBy:string,override:boolean,reason:string){if(!mayReview(a))return 'No tienes permiso para validar.';if(!reason.trim())return 'Agrega una observación de revisión.';if(submittedBy===a.userId&&!(a.role==='owner'&&override))return 'La revisión debe realizarla otra persona. El propietario puede registrar una excepción justificada.';return null}
