import { sqliteTable, text, integer, index, uniqueIndex } from 'drizzle-orm/sqlite-core';
export const records=sqliteTable('quality_records',{id:text('id').primaryKey(),owner:text('owner').notNull(),space:text('space').notNull(),kind:text('kind').notNull(),title:text('title').notNull(),area:text('area').notNull(),responsible:text('responsible').notNull(),due:text('due').notNull(),status:text('status').notNull(),priority:text('priority').notNull(),code:text('code').notNull(),evidence:text('evidence').notNull(),notes:text('notes').notNull(),created:text('created').notNull(),updated:text('updated').notNull(),createdBy:text('created_by').notNull().default(''),submittedBy:text('submitted_by').notNull().default('')},t=>[index('idx_records_owner_space').on(t.owner,t.space)]);
export const spaces=sqliteTable('quality_spaces',{id:text('id').primaryKey(),owner:text('owner').notNull(),slot:text('slot').notNull(),name:text('name').notNull(),company:text('company').notNull()},t=>[index('idx_spaces_owner').on(t.owner)]);
export const audit=sqliteTable('quality_audit',{id:text('id').primaryKey(),owner:text('owner').notNull(),record:text('record').notNull(),action:text('action').notNull(),before:text('before').notNull(),after:text('after').notNull(),at:text('at').notNull(),actor:text('actor').notNull().default(''),space:text('space').notNull().default('')},t=>[index('idx_audit_owner').on(t.owner)]);
export const learningEntities=sqliteTable('learning_entities',{id:text('id').primaryKey(),owner:text('owner').notNull(),kind:text('kind').notNull(),payload:text('payload').notNull(),created:text('created').notNull(),updated:text('updated').notNull()},t=>[index('idx_learning_owner_kind').on(t.owner,t.kind)]);

export const organizations=sqliteTable('organizations',{id:text('id').primaryKey(),ownerId:text('owner_id').notNull(),ownerEmail:text('owner_email').notNull(),created:text('created').notNull()});
export const memberships=sqliteTable('memberships',{id:text('id').primaryKey(),owner:text('owner').notNull(),email:text('email').notNull(),userId:text('user_id').notNull().default(''),name:text('name').notNull(),role:text('role').notNull(),spaces:text('spaces').notNull(),areas:text('areas').notNull(),employeeId:text('employee_id').notNull(),active:text('active').notNull(),created:text('created').notNull(),updated:text('updated').notNull()},t=>[uniqueIndex('idx_members_owner_email').on(t.owner,t.email)]);
export const storedFiles=sqliteTable('stored_files',{id:text('id').primaryKey(),owner:text('owner').notNull(),space:text('space').notNull(),area:text('area').notNull(),name:text('name').notNull(),mime:text('mime').notNull(),size:text('size').notNull(),key:text('key').notNull(),createdBy:text('created_by').notNull(),created:text('created').notNull()},t=>[index('idx_files_owner_space').on(t.owner,t.space)]);
export const backups=sqliteTable('backups',{id:text('id').primaryKey(),owner:text('owner').notNull(),key:text('key').notNull(),created:text('created').notNull(),reason:text('reason').notNull(),count:text('count').notNull()},t=>[index('idx_backups_owner').on(t.owner)]);

export const authUsers=sqliteTable('auth_users',{id:text('id').primaryKey(),email:text('email').notNull().unique(),name:text('name').notNull(),passwordHash:text('password_hash').notNull(),created:text('created').notNull(),updated:text('updated').notNull()});
export const authSessions=sqliteTable('auth_sessions',{tokenHash:text('token_hash').primaryKey(),userId:text('user_id').notNull().references(()=>authUsers.id),created:text('created').notNull(),expires:text('expires').notNull()},t=>[index('idx_auth_sessions_user').on(t.userId),index('idx_auth_sessions_expiry').on(t.expires)]);
export const authTokens=sqliteTable('auth_tokens',{tokenHash:text('token_hash').primaryKey(),email:text('email').notNull(),userId:text('user_id').notNull(),purpose:text('purpose').notNull(),created:text('created').notNull(),expires:text('expires').notNull()},t=>[index('idx_auth_tokens_email').on(t.email)]);
export const authLimits=sqliteTable('auth_limits',{key:text('key').primaryKey(),attempts:integer('attempts').notNull(),expires:text('expires').notNull()});
